logging:
  version: 1
  disable_existing_loggers: False

  formatters:
      simple:
          format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
          datefmt: '%Y-%m-%d %H:%M:%S'
      detailed:
          format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
          datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
      console:
          class: logging.StreamHandler
          level: DEBUG
          formatter: detailed
          stream: ext://sys.stdout

      file:
          class: logging.FileHandler
          level: INFO
          formatter: detailed
          filename: myapp.log
          mode: a

  loggers:
      development:
          level: DEBUG
          handlers: [console]
          propagate: no

      staging:
          level: INFO
          handlers: [console, file]
          propagate: no

      production:
          level: WARNING
          handlers: [file]
          propagate: no

  root:
      level: DEBUG
      handlers: [console]

application:
  version: 0.0.1
  project: 'template'
  copyright: '{{cookiecutter.year}}, {{cookiecutter.author}}'
  author: '{{cookiecutter.author}}'

  database_conn_string: sqlite:///database.db
